[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://ehabgm.online"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
